### ISSUE TITLE
Cynet Warning

### ISSUE THREAD

**Issue by dam-paw** [tsx4k/Fancy-Browser-Selector#12]
Cynet Alert Notification when using browser profiles

![image](https://user-images.githubusercontent.com/64251200/229749143-89bbd021-5d0a-483a-a8d4-f914497e1562.png)

**Comment by tsx4k** [comment]
According to the information on Cynet Website at:
[https://help.cynet.com/en/articles/118-memory-protection-alerts](https://help.cynet.com/en/articles/118-memory-protection-alerts)

Browser config files are just monitored by Cynet and that's why the alert was shown. Not sure if we can do anything about it, but a blind try is opening that config with extra FileAccess.Read [only] flag, maybe this will help. Please try it on the next release.

**Comment by dam-paw** [comment]
In version  v1.2.8494.32859 I still have the alert.
